#!/bin/python3
# This script auto-generates the uri_known_tlds_default.cpp file with an
# up-to-date list obtained from https://data.iana.org/TLD/tlds-alpha-by-domain.txt
import http.client

OUTPUT_PATH = "../src/libstrtb/uri_known_tlds_default.cpp"
MAX_SIZE = 50 * 1024

print("NOTE: Make sure you're running this file from the tools directory, otherwise the generated file will be misplaced.")
print("Acquiring new TLD list from https://data.iana.org/TLD/tlds-alpha-by-domain.txt")
conn = http.client.HTTPSConnection("data.iana.org")
conn.request("GET", "/TLD/tlds-alpha-by-domain.txt")
response = conn.getresponse()
print("Server responded with", response.status, response.reason)
if response.status != 200:
  print("Exiting due to server error")
  exit(1)
data = response.read()
if len(data) > MAX_SIZE:
  print("ERROR: Data exceeds the size limit of", MAX_SIZE, "bytes.")
  exit(2)
if data.find(b'"') != -1:
  print("ERROR: Found quotes in received data")
  exit(2)
lines = data.split(b'\n')
print("File contents:", len(data), "bytes received,", len(lines), "lines")

print("Writing to", repr(OUTPUT_PATH))
with open(OUTPUT_PATH, "wb") as f:
  f.write(b'// This file was autogenerated using the script at ../../tools/update_known_tlds_default.py\n')
  f.write(b'// Using the TLD list from https://data.iana.org/TLD/tlds-alpha-by-domain.txt\n')
  f.write(b'#include "uri.h"\n\n')
  f.write(b'const char strtb::uri::known_tlds_default[] = ')
  for l in lines[:-1]:
    f.write(b'"')
    f.write(l)
    f.write(b'\\n"\n')
  f.write(b'"')
  f.write(lines[-1])
  f.write(b'";\n\nextern const size_t strtb::uri::known_tlds_default_length = sizeof(known_tlds_default);\n')

print("File was written. Make sure to open the file and confirm that its contents seem correct.")
