#ifndef VERSION_H
#define VERSION_H

#define STRTB_VERSION_MAJOR "0"
#define STRTB_VERSION_MINOR "2"
#define STRTB_VERSION_PATCH "0"
#define STRTB_VERSION_PHASE "alpha"
#define STRTB_VERSION_FULL STRTB_VERSION_MAJOR "." STRTB_VERSION_MINOR "." STRTB_VERSION_PATCH "-" STRTB_VERSION_PHASE

#endif // VERSION_H
